version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - "4050:4050"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/footleague
      SERVER_PORT: 4050
    volumes:
      - ./src:/app/src
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
